# charts/istio/templates/gateway.yaml
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.gateway.namespace }}
  labels:
    app: {{ .Values.gateway.name }}
spec:
  selector:
    istio: ingressgateway  # Use the default Istio ingress gateway
  servers:
  - port:
      number: {{ (.port | default dict).number | default 80 }}
      name: {{ (.port | default dict).name | default "http" }}
      protocol: {{ (.port | default dict).protocol | default "HTTP" }}
    hosts:
    {{- range .Values.gateway.hosts }}
    - {{ . | quote }}
    {{- end }}
    {{- if .tls }}
    tls:
      mode: {{ .tls.mode | default "SIMPLE" }}
      {{- if .tls.credentialName }}
      credentialName: {{ .tls.credentialName }}
      {{- end }}
    {{- end }}